# bake_assets.cmake -- bake studio/data into a C table so the app is one file.
#
#   cmake -DDATA_DIR=<dir> -DOUT=<file> -P tools/bake_assets.cmake
#
# The sibling of tools/bake_embedded.cmake, which does the same for lua/. Two
# scripts rather than one because the keys differ and the difference matters:
# bake_embedded keys by *module name* (lua/gold/str.lua -> "gold/str"), because
# everything it bakes is a Lua module. This keys by *path* including the
# extension, because studio/data holds three TrueType fonts as well as sixty-odd
# Lua files, and "fonts/font.ttf" has no module name to be stripped to.
#
# file(READ ... HEX) is binary-safe -- it is already how bake_embedded avoids
# mangling quotes and backslashes in Lua source -- so the fonts come through a
# byte at a time with no special casing.

if(NOT DATA_DIR OR NOT OUT)
  message(FATAL_ERROR "usage: cmake -DDATA_DIR=<dir> -DOUT=<file> -P bake_assets.cmake")
endif()

file(GLOB_RECURSE asset_files RELATIVE "${DATA_DIR}" "${DATA_DIR}/*")
list(SORT asset_files)

set(body "/* generated by tools/bake_assets.cmake -- do not edit */\n")
string(APPEND body "#include \"assets.h\"\n#include <string.h>\n#include <stddef.h>\n\n")

set(i 0)
foreach(f IN LISTS asset_files)
  file(READ "${DATA_DIR}/${f}" hex HEX)
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
  # Trailing sentinel so an empty file still yields a valid initializer list;
  # the length below subtracts it. It also means Lua source handed to
  # luaL_loadbuffer is NUL-terminated, which costs nothing and avoids a class
  # of reader bug.
  string(APPEND body "static const unsigned char ast_${i}[] = {${bytes}0};\n")
  math(EXPR i "${i} + 1")
endforeach()

string(APPEND body "\nstatic const struct { const char *name; const unsigned char *data; size_t len; } asset_table[] = {\n")
set(i 0)
foreach(f IN LISTS asset_files)
  string(APPEND body "  { \"${f}\", ast_${i}, sizeof(ast_${i}) - 1 },\n")
  math(EXPR i "${i} + 1")
endforeach()
string(APPEND body "};\n")

string(APPEND body "
const void *studio_asset_get(const char *name, size_t *len) {
  size_t n = sizeof(asset_table) / sizeof(asset_table[0]);
  for (size_t i = 0; i < n; i++) {
    if (strcmp(asset_table[i].name, name) == 0) {
      if (len) *len = asset_table[i].len;
      return asset_table[i].data;
    }
  }
  return NULL;
}

size_t studio_asset_count(void) {
  return sizeof(asset_table) / sizeof(asset_table[0]);
}

const char *studio_asset_name(size_t i) {
  size_t n = sizeof(asset_table) / sizeof(asset_table[0]);
  return i < n ? asset_table[i].name : NULL;
}
")

# Only rewrite when the content actually changed, so ninja does not relink on
# every configure.
if(EXISTS "${OUT}")
  file(READ "${OUT}" existing)
  if(existing STREQUAL body)
    return()
  endif()
endif()
file(WRITE "${OUT}" "${body}")
