# bake_embedded.cmake -- portable replacement for gen_embedded.sh.
#
#   cmake -DLUA_DIR=<dir> -DOUT=<file> -P tools/bake_embedded.cmake
#
# Bakes every <LUA_DIR>/**/*.lua into a C lookup table keyed by module name
# (path relative to LUA_DIR without the .lua suffix, e.g. "boot", "gold/str").
#
# *.json is baked too, keyed WITH its extension ("models.json"), so it is data
# rather than a module: the searcher only ever asks for module names, and
# boggart.embedded("models.json") hands back the bytes. That is how the seeded
# model catalog ships -- one format for the seed, the export and the import,
# so the built-in list is a worked example of the file you would write.
# Emits byte-for-byte the same structure as gen_embedded.sh, but uses only
# CMake built-ins -- no sh, od, awk, sed or find -- so it works on native
# Windows where those do not exist.

if(NOT LUA_DIR OR NOT OUT)
  message(FATAL_ERROR "usage: cmake -DLUA_DIR=<dir> -DOUT=<file> -P bake_embedded.cmake")
endif()

file(GLOB_RECURSE lua_files RELATIVE "${LUA_DIR}" "${LUA_DIR}/*.lua")
file(GLOB_RECURSE data_files RELATIVE "${LUA_DIR}" "${LUA_DIR}/*.json")
list(APPEND lua_files ${data_files})
list(SORT lua_files)

set(body "/* generated by tools/bake_embedded.cmake -- do not edit */\n")
string(APPEND body "#include \"embedded.h\"\n#include <string.h>\n#include <stddef.h>\n\n")

set(i 0)
foreach(f IN LISTS lua_files)
  # HEX gives one lowercase byte pair per source byte, so this is binary-safe
  # and never mangles embedded quotes, backslashes or newlines.
  file(READ "${LUA_DIR}/${f}" hex HEX)
  string(REGEX REPLACE "(..)" "0x\\1," bytes "${hex}")
  # Trailing sentinel byte so an empty .lua file still yields a valid C
  # initializer list; the table length below subtracts it.
  string(APPEND body "static const unsigned char emb_${i}[] = {${bytes}0};\n")
  math(EXPR i "${i} + 1")
endforeach()

string(APPEND body "\nstatic const struct { const char *name; const unsigned char *data; size_t len; } emb_table[] = {\n")
set(i 0)
foreach(f IN LISTS lua_files)
  # .lua files are keyed by module name; .json keeps its extension so it can
  # never collide with a module and is obviously data at the call site.
  string(REGEX REPLACE "\\.lua$" "" name "${f}")
  string(APPEND body "  { \"${name}\", emb_${i}, sizeof(emb_${i}) - 1 },\n")
  math(EXPR i "${i} + 1")
endforeach()
string(APPEND body "};\n")

string(APPEND body "
const char *boggart_embedded_get(const char *name, size_t *len) {
  size_t n = sizeof(emb_table) / sizeof(emb_table[0]);
  for (size_t i = 0; i < n; i++) {
    if (strcmp(emb_table[i].name, name) == 0) {
      if (len) *len = emb_table[i].len;
      return (const char *)emb_table[i].data;
    }
  }
  return NULL;
}

size_t boggart_embedded_count(void) {
  return sizeof(emb_table) / sizeof(emb_table[0]);
}

const char *boggart_embedded_name(size_t i) {
  size_t n = sizeof(emb_table) / sizeof(emb_table[0]);
  return i < n ? emb_table[i].name : NULL;
}
")

# Only rewrite when the content actually changed, so ninja does not relink on
# every configure.
if(EXISTS "${OUT}")
  file(READ "${OUT}" existing)
  if(existing STREQUAL body)
    return()
  endif()
endif()
file(WRITE "${OUT}" "${body}")
