#!/bin/sh
# gen_embedded.sh LUA_DIR > embedded.c
# Bakes every lua/**/*.lua file into a C lookup table keyed by module name
# (path relative to LUA_DIR without the .lua suffix, e.g. "boot", "tools/wc").
set -e
LUADIR="$1"
[ -n "$LUADIR" ] || { echo "usage: $0 LUA_DIR" >&2; exit 1; }

files=$(cd "$LUADIR" && find . -name '*.lua' | sed 's|^\./||' | sort)

echo '/* generated by tools/gen_embedded.sh -- do not edit */'
echo '#include "embedded.h"'
echo '#include <string.h>'
echo '#include <stddef.h>'
echo ''

i=0
for f in $files; do
  echo "static const unsigned char emb_${i}[] = {"
  od -An -v -tu1 "$LUADIR/$f" | tr -s ' ' '\n' | grep -v '^$' | awk '{ printf "%s,", $0 }'
  # trailing sentinel byte so an empty .lua file still yields a valid (non-empty)
  # C initializer list; the table length below subtracts it.
  echo "0"
  echo "};"
  i=$((i + 1))
done

echo ''
echo 'static const struct { const char *name; const unsigned char *data; size_t len; } emb_table[] = {'
i=0
for f in $files; do
  name=$(echo "$f" | sed 's|\.lua$||')
  echo "  { \"${name}\", emb_${i}, sizeof(emb_${i}) - 1 },"
  i=$((i + 1))
done
echo '};'

cat <<'EOF'

const char *boggart_embedded_get(const char *name, size_t *len) {
  size_t n = sizeof(emb_table) / sizeof(emb_table[0]);
  for (size_t i = 0; i < n; i++) {
    if (strcmp(emb_table[i].name, name) == 0) {
      if (len) *len = emb_table[i].len;
      return (const char *)emb_table[i].data;
    }
  }
  return NULL;
}

size_t boggart_embedded_count(void) {
  return sizeof(emb_table) / sizeof(emb_table[0]);
}

const char *boggart_embedded_name(size_t i) {
  size_t n = sizeof(emb_table) / sizeof(emb_table[0]);
  return i < n ? emb_table[i].name : NULL;
}
EOF
